/* Processing evidence browser; source outcomes never change the aroma vectors. */
(() => {
'use strict';
const P=window.FLAVOR_PROCESSING,D=window.FLAVOR_DATA;
if(!P||!window.FlavorProcessingEngine)return;
const engine=window.FlavorProcessingEngine.create(P),$=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=v=>typeof v==='object'?JSON.stringify(v,null,2):String(v??'未报告');
const domains={aroma:'香气感知',taste:'味觉',texture:'质地 / 口感',chemical:'化学测量 / 分子',color:'颜色',other:'其他',chemesthesis:'刺激感'};
const directions={increase:'增加',decrease:'减少',emerge:'形成 / 出现',change:'发生变化',no_significant_change:'未见显著变化',conditional:'取决于条件',presence:'处理后具有'};
const arrows={increase:'↑',decrease:'↓',emerge:'＋',change:'↔',no_significant_change:'≈',conditional:'◇',presence:'●'};
const kinds={change:'前后变化',condition_dependency:'条件依赖',state_profile:'处理后状态'};
const indexLabels={method:'加工方式',effect:'加工效果',ingredient:'食材'};
const state={index:'method',query:'',source:'',kind:'',domain:'',groupKey:'',page:0,catalogId:null};
const byId=new Map(P.records.map(r=>[r.id,r])),catalog=new Map(D.ingredients.map(i=>[i.id,i]));
const unique=a=>[...new Set(a.filter(x=>x!==null&&x!==undefined&&x!==''))];
const effects=r=>r.normalizedEffects||r.effects||[];
const effectKey=e=>`${e.domain}|${e.label}|${e.direction}`;
let snapshot={records:[],groups:[],selected:[],group:null};
function download(content,name,type='application/json;charset=utf-8'){const body=typeof content==='string'?content:JSON.stringify(content,null,2);const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function raw(v,label='完整记录与原始字段'){return `<details class="raw-record"><summary>${esc(label)}</summary><pre>${esc(JSON.stringify(v,null,2))}</pre></details>`;}
function sourceLinks(r){const s=r.source||{};let links=(s.pdfPages||[]).map(n=>`<a href="../${encodeURIComponent(D.meta.sourcePdf)}#page=${Number(n)||1}" target="_blank" rel="noopener">原书 PDF ${esc(n)} 页 ↗</a>`);if(/^https:\/\//.test(s.url||''))links.push(`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.journal||'原始研究')} ${esc(s.year||'')} ↗</a>`);return links.join('');}
function badge(e,interactive=false){const text=`${arrows[e.direction]||'◇'} ${e.label} · ${directions[e.direction]||e.direction}`;return interactive?`<button type="button" class="process-effect ${esc(e.direction)}" data-process-effect="${esc(effectKey(e))}" title="${esc(domains[e.domain]||e.domain)} · 原描述：${esc(e.originalLabel||e.label)} · ${esc(e.detail)}">${esc(text)}</button>`:`<span class="process-effect ${esc(e.direction)}" title="${esc(domains[e.domain]||e.domain)}">${esc(text)}</span>`;}
function chips(items,kind){const make=s=>`<button class="process-link-chip" type="button" data-process-jump="${kind}" data-process-label="${esc(s)}">${esc(s)}</button>`;return items.length>4?items.slice(0,4).map(make).join('')+`<details class="process-more"><summary>另 ${items.length-4} 项</summary><div>${items.slice(4).map(make).join('')}</div></details>`:items.map(make).join('');}
function imageFor(name,records){const links=records.flatMap(r=>r.ingredientLinks||[]);const direct=D.ingredients.find(i=>i.displayName===name||i.name===name)||links.map(l=>catalog.get(l.ingredientId)).find(Boolean);return direct?`<img src="${esc(window.FLAVOR_ASSETS?.[direct.id]||direct.image)}" width="40" height="40" loading="lazy" alt="${esc(direct.displayName)}食材插画">`:'';}
function activeRecords(){let records=engine.filter(state);if(state.catalogId){const ids=new Set(engine.forIngredient(state.catalogId).map(r=>r.id));records=records.filter(r=>ids.has(r.id));}return records;}
function groupRows(groups){if(!groups.length)return '<div class="process-empty"><span>⌕</span><h4>当前条件下，没有可索引的记录。</h4><p>缺少证据仍保留为未知；可以清除筛选，再从另一条路径寻找。</p></div>';
const heads=state.index==='method'?['加工方式','涉及食材','相近效果与方向','记录']:state.index==='effect'?['加工效果','涉及食材','相关加工方式','记录']:['食材 / 原料语境','加工方式','效果与方向','记录'];
return `<table class="process-index-table"><caption class="sr-only">${indexLabels[state.index]}索引，当前筛选范围内的全部分组</caption><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${groups.map((g,ix)=>{const rows=g.records||g.recordIds.map(id=>byId.get(id)).filter(Boolean),ingredientNames=unique(rows.flatMap(r=>r.ingredientNames)),methods=unique(rows.flatMap(r=>r.methods));const allEffects=[...new Map(rows.flatMap(effects).map(e=>[effectKey(e),e])).values()];const badgeList=allEffects.slice(0,4).map(e=>badge(e,true)).join('')+(allEffects.length>4?`<details class="process-more"><summary>另 ${allEffects.length-4} 类效果</summary><div>${allEffects.slice(4).map(e=>badge(e,true)).join('')}</div></details>`:'');return `<tr class="${state.groupKey===g.key?'is-selected':''}"><th scope="row"><button type="button" class="process-group-button" data-process-group="${esc(g.key)}">${state.index==='ingredient'?imageFor(g.label,rows):`<span class="process-row-number">${String(ix+1).padStart(2,'0')}</span>`}<span>${esc(g.label)}${state.index==='effect'?`<small>${esc(domains[g.domain]||g.domain)} · ${esc(directions[g.direction]||g.direction)}</small>`:''}</span><b>↗</b></button></th><td><div class="process-cell-chips">${state.index==='ingredient'?chips(methods,'method'):chips(ingredientNames,'ingredient')}</div></td><td><div class="process-cell-chips">${state.index==='effect'?chips(methods,'method'):badgeList}</div></td><td><button type="button" class="process-count-button" data-process-group="${esc(g.key)}" aria-label="查看${esc(g.label)}的${rows.length}条记录">${rows.length}<span>条</span></button></td></tr>`;}).join('')}</tbody></table>`;
}
function detailFields(r){const values=r.reportedValues||[];const links=r.ingredientLinks||[];return `<div class="process-detail-fields"><dl><dt>处理条件</dt><dd>${esc(val(r.conditions))}</dd><dt>机制与解释</dt><dd>${esc(val(r.mechanism))}</dd><dt>适用边界</dt><dd>${esc(val(r.limitations))}</dd></dl>${values.length?`<h4>来源明示的数值 · 保留单位与条件</h4><div class="process-values">${values.map(v=>`<div><strong>${esc(v.metric||v.attribute||v.label||'原文数值')}</strong><span>${esc(val(v.value??v.values??v.range??v))} ${esc(v.unit||'')}</span><p>${esc(v.context||v.note||'见完整原记录的适用条件')}</p></div>`).join('')}</div>`:'<p class="process-no-number">此条未提取可直接使用的定量变化值。</p>'}<h4>出处与证据范围</h4><p>${esc(r.source?.title||'食物風味搭配科學')}${r.source?.doi?'<br>DOI '+esc(r.source.doi):''}${r.source?.evidenceIds?.length?'<br>属性证据 '+esc(r.source.evidenceIds.join('、')):''}${r.source?.bookPages?.length?'<br>书内页码 '+esc(r.source.bookPages.join('、')):''}</p><p>${esc(r.evidenceLevel||'详见来源')} ${r.source?.kind==='research'&&r.source?.extractionScope==='study_summary'?'· 当前收录研究结果摘要与条件，未录入全文原始测量矩阵。':''}</p><div class="process-source-links">${sourceLinks(r)}</div>${links.length?`<details><summary>与食材库的 ${links.length} 项关联（保留身份和条件）</summary><div class="process-catalog-links">${links.map(l=>`<div><button type="button" class="text-button" data-detail="${esc(l.ingredientId)}">${esc(catalog.get(l.ingredientId)?.displayName||l.ingredientId)} ↗</button><span>${l.kind==='exact_name'?'同名关联':l.kind==='alias_name'?'别名关联':'相关语境'}</span><p>${esc(l.reason||'需核对原加工条件；不转移定量值。')}</p></div>`).join('')}</div></details>`:'<p class="process-no-number">尚未关联圆点食材身份；这条证据独立保留。</p>'}${raw(r)}</div>`;}
function card(r,expanded=false){const ef=effects(r);return `<article class="process-card" id="process-card-${esc(r.id)}"><div class="process-card-top"><span class="process-record-id">${esc(r.id)}</span><span class="process-source-tag ${r.source?.kind==='research'?'is-research':''}">${r.source?.kind==='research'?'研究文献':'书中证据'} · ${esc(kinds[r.recordKind]||r.recordKind)}</span></div><h4>${esc(r.title)}</h4><div class="process-methods">${chips(r.methods||[],'method')}</div><div class="process-transition"><div><small>${r.recordKind==='state_profile'?'比较基线':'处理前 / 比较对象'}</small><p>${esc(r.before||'来源未报告')}</p></div><span aria-hidden="true">→</span><div><small>处理后 / 条件结果</small><p>${esc(r.after||'见来源说明')}</p></div></div><p class="process-summary">${esc(r.summary)}</p><div class="process-outcomes">${ef.map(e=>`<div><span class="process-domain">${esc(domains[e.domain]||e.domain)}</span>${badge(e,true)}<p>${esc(e.detail)}</p>${e.originalLabel&&e.originalLabel!==e.label?`<small class="process-original-label">原描述：${esc(e.originalLabel)}</small>`:''}</div>`).join('')||'<p class="process-no-number">未提取明确变化方向，保留状态和条件。</p>'}</div>${state.catalogId?`<p class="process-linked-note">食材关联：${unique((r.ingredientLinks||[]).filter(l=>l.ingredientId===state.catalogId).map(l=>l.kind==='related_context'?'相关语境，需核对品种与状态':'同名/别名，仍保留条件')).join('；')}</p>`:''}<details class="process-detail" ${expanded?'open':''}><summary>处理条件、机制与全部出处 <span>＋</span></summary>${detailFields(r)}</details><div class="process-card-footer"><div class="process-source-links">${sourceLinks(r)}</div><button type="button" class="text-button" data-process-attach="${esc(r.id)}">记入本次试做 ＋</button></div></article>`;}
function render(){
 const rows=activeRecords();let groups=engine.groups(state.index,rows);if(state.index==='effect'&&state.domain)groups=groups.filter(g=>g.domain===state.domain);
 let group=groups.find(g=>g.key===state.groupKey);if(!group)state.groupKey='';let selected=group?(group.records||group.recordIds.map(id=>byId.get(id))):rows;
 snapshot={records:rows,groups,selected,group};
 document.querySelectorAll('[data-process-index]').forEach(b=>{b.classList.toggle('is-active',b.dataset.processIndex===state.index);b.setAttribute('aria-pressed',String(b.dataset.processIndex===state.index));});
 $('processingNavCount').textContent=P.records.length;
 $('processIndexTitle').textContent=indexLabels[state.index]+'索引';
 $('processingIndexCount').textContent=`${groups.length} 个索引组 · 当前 ${rows.length} 条独立记录 / 库内 ${P.records.length} 条`;
 $('processingIndexTable').innerHTML=groupRows(groups);
 $('processingIndexNote').textContent=state.index==='effect'?'按维度、相近描述和变化方向分组；增加、减少、无显著变化分别保留。同一效果不表示强度、机制或适用条件相同。':'一条记录可以涉及多种方式、效果和食材；各组数量存在重叠，不能相加当作总数。点索引名称查看具体路径。';
 $('processingContext').hidden=!state.catalogId;
 if(state.catalogId)$('processingContext').innerHTML=`正在查看 <b>${esc(catalog.get(state.catalogId)?.displayName||state.catalogId)}</b> 的关联线索。同名、别名与相关语境分别标注；其他处理状态不会自动成为此食材的属性。`;
 $('processResultsTitle').textContent=group?`${group.label} · 加工记录`:'全部加工记录';
 $('processClearGroup').hidden=!group;
 const totalPages=Math.max(1,Math.ceil(selected.length/6));state.page=Math.min(state.page,totalPages-1);const pageRows=selected.slice(state.page*6,state.page*6+6);
 $('processingResultCount').textContent=`${selected.length} 条记录${selected.length?` · 显示 ${state.page*6+1}–${state.page*6+pageRows.length} · 第 ${state.page+1}/${totalPages} 页`:''} · 条件与原文逐条保留`;
 $('processingCards').innerHTML=pageRows.map(r=>card(r)).join('')||'<div class="process-empty"><h4>尚无对应的加工证据。</h4><p>这不表示加工没有影响；当前资料无法给出结论。</p></div>';
 $('processingPagination').innerHTML=selected.length>6?`<button type="button" data-process-page="${state.page-1}" ${state.page===0?'disabled':''}>上一页</button><label>第 <input id="processPageInput" type="number" min="1" max="${totalPages}" value="${state.page+1}" aria-label="加工记录页码"> / ${totalPages} 页</label><button type="button" data-process-page-go>前往</button><button type="button" data-process-page="${state.page+1}" ${state.page===totalPages-1?'disabled':''}>下一页</button>`:'';
}
function reset(){Object.assign(state,{query:'',source:'',kind:'',domain:'',groupKey:'',page:0,catalogId:null});$('processingSearch').value='';$('processingSource').value='';$('processingKind').value='';$('processingDomain').value='';}
function jump(index,key){state.index=index;state.groupKey=key;state.page=0;if(index==='effect'&&state.domain){state.domain=key.split('|')[0];$('processingDomain').value=state.domain;}$('sourceDialog').close();window.FLAVOR_ENGINE.setView('processing');render();$('processingResults').scrollIntoView({behavior:'smooth',block:'start'});}
function openForIngredient(id){reset();state.catalogId=id;state.index='method';$('sourceDialog').close();window.FLAVOR_ENGINE.setView('processing');$('processingView').scrollIntoView({behavior:'smooth',block:'start'});}
function openRecord(id){const r=byId.get(id);if(!r)return;const container=$('sourceDialogContent');container.innerHTML=`<h2 id="sourceDialogTitle">加工依据 · ${esc(r.title)}</h2>${card(r,true)}`;if(!$('sourceDialog').open)$('sourceDialog').showModal();}
function exportSelection(){return {schema:'flavour-processing-selection-v1',filters:{...state},index:state.index,group:snapshot.group?{key:snapshot.group.key,label:snapshot.group.label}:null,recordCount:snapshot.selected.length,records:snapshot.selected,coverage:P.coverage||P.meta,method:'Source conditions and original records retained. Similar effect groups are navigational, not pooled estimates or transferable coefficients.'};}
function csvIndex(){const header=[indexLabels[state.index],'维度','方向','独立记录数','食材','加工方式','记录ID','当前筛选'];const rows=snapshot.groups.map(g=>{const records=g.records||g.recordIds.map(id=>byId.get(id));return[g.label,domains[g.domain]||g.domain||'',directions[g.direction]||g.direction||'',records.length,unique(records.flatMap(r=>r.ingredientNames)).join('；'),unique(records.flatMap(r=>r.methods)).join('；'),records.map(r=>r.id).join('；'),JSON.stringify({...state,groupKey:''})];});const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return '\ufeff'+[header,...rows].map(r=>r.map(cell).join(',')).join('\r\n');}
for(const [id,key] of [['processingSearch','query'],['processingSource','source'],['processingKind','kind'],['processingDomain','domain']])$(id).addEventListener(id==='processingSearch'?'input':'change',e=>{state[key]=e.target.value;state.groupKey='';state.page=0;render();});
$('processReset').onclick=()=>{reset();render();};$('processClearGroup').onclick=()=>{state.groupKey='';state.page=0;render();};
$('processExportSelection').onclick=()=>download(exportSelection(),'加工记录_当前筛选.json');
$('processExportAll').onclick=()=>download(P,'加工与风味变化_完整数据.json');
$('processExportIndex').onclick=()=>download(csvIndex(),`加工索引_${indexLabels[state.index]}_当前筛选.csv`,'text/csv;charset=utf-8');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.processIndex){state.index=b.dataset.processIndex;state.groupKey='';state.page=0;render();}
 else if(b.dataset.processGroup){jump(state.index,b.dataset.processGroup);}
 else if(b.dataset.processEffect){jump('effect',b.dataset.processEffect);}
 else if(b.dataset.processJump){const groups=engine.groups(b.dataset.processJump,activeRecords()),group=groups.find(g=>g.label===b.dataset.processLabel||g.originalLabels?.includes(b.dataset.processLabel));if(group)jump(b.dataset.processJump,group.key);}
 else if(b.dataset.processIngredient){openForIngredient(b.dataset.processIngredient);}
 else if(b.dataset.processRecord){openRecord(b.dataset.processRecord);}
 else if(b.dataset.processAttach){window.FLAVOR_ENGINE.appendProcessing(byId.get(b.dataset.processAttach));b.textContent='已记入试做 ✓';}
 else if(b.dataset.processPage!==undefined){state.page=Math.max(0,+b.dataset.processPage);render();$('processingResults').scrollIntoView({behavior:'smooth',block:'start'});}
 else if(b.hasAttribute('data-process-page-go')){goPage();}
});
function goPage(){state.page=Math.max(0,Math.trunc(Number($('processPageInput').value)||1)-1);render();$('processingResults').scrollIntoView({behavior:'smooth',block:'start'});}
document.addEventListener('keydown',e=>{if(e.target.id==='processPageInput'&&e.key==='Enter')goPage();});
const bookCount=P.records.filter(r=>r.source?.kind==='book').length,studies=unique(P.records.filter(r=>r.source?.kind==='research').map(r=>r.source.doi||r.source.title)).length;
$('processingStats').innerHTML=`<span><b>${P.records.length}</b> 条加工与条件记录</span><span><b>${bookCount}</b> 条书中记录</span><span><b>${studies}</b> 篇原始研究</span><span class="process-stats-note">香气 · 味觉 · 质地 · 分子 · 颜色</span>`;
$('processingMethodNote').innerHTML=`<p>完整保留当前已提取的加工相关内容与补充研究。${bookCount} 条书中记录来自现有属性证据的逐条分类及补充原页；${studies} 篇研究保留实验条件与结果边界。记录数是拆分后的条件记录数，不能当作独立实验数；未宣称全书或全部加工文献已穷尽。</p><p>相近效果仅用于检索；每条记录继续保留原描述、方向和证据维度。化合物峰面积、挥发物释放量、感官评价分别解释。无显著变化不等于没有任何影响；没有比较基线的处理后状态不会补造增减。</p><p>“记入本次试做”将完整加工依据关联到当前提案，随保存和导出保留。实际工艺、用量与评价仍由试做记录填写，页面的香气来源图不会凭定性描述自动增减数值。</p>${raw({coverage:P.coverage,metrics:P.metrics,normalization:P.normalization},'本版覆盖、分组规则与合并统计')}${raw(P.audit253||P.audit||P.bookAudit||[],'原属性证据的加工分类审计')}`;
window.FLAVOR_PROCESS_UI={render,openForIngredient,openRecord,exportSelection,csvIndex,getState:()=>({...state})};
render();
})();
